---
title: "Ćwiczenia 5"
output:
  html_document: default
  pdf_document: default
date: "2023-11-20"
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(nlstools)
library(robustbase)
```

### Zadanie 1

```{r}
df <- DAAG::litters
mm <- lm(brainwt ~ lsize + bodywt, data = df)
summary(mm)
```

Bardzo mocno skorelowane zmienne objaśniające $R^2>90\%$ dla modelu wyjaśniającego
wielkość miotu od masy ciała

```{r}
car::vif(mm)
```

### Zadanie 2

```{r}
df <- carData::USPop
```

Samemu przez `stats::optim`:

```{r}
fn <- function(par = c(1, 1, 1)) {
    a <- par[1]
    b <- par[2]
    c <- par[3]
    
    mean((df$population - a / (1 + exp((b - df$year)/ c))) ^ 2)
}

op <- optim(fn = fn, par = c(200, 2000, 100), 
            hessian = TRUE,
            method = "Nelder-Mead",
            control = list(maxit = 50000, 
                           abstol = .Machine$double.eps, trace = TRUE))
lln <- function(x) {
  op$par[1] / (1 + exp((op$par[2]-x)/op$par[3]))
}

df |>
  ggplot(aes(y = population, x = year)) +
  geom_point() +
  geom_line(data = data.frame(x = seq(from = 1790, to = 2000, by = 1),
                              y = lln(seq(from = 1790, to = 2000, by = 1))),
                 inherit.aes = FALSE,
                 aes(y = y, x = x))
```

Using `stats::nls`:

```{r}
mm <- nls(population ~ SSlogis(year, a, b, c), data = df)


df |>
  ggplot(aes(y = population, x = year)) +
  geom_point() +
  stat_function(fun = function(x) SSlogis(x, coef(mm)[1], coef(mm)[2], coef(mm)[3]))
```


```{r}
par(mfrow = c(2, 2))
plot(nlsResiduals(mm), 2) # Standardized residuals
plot(nlsResiduals(mm), 4) # Auto-correlation of residuals
plot(nlsResiduals(mm), 5) # Normality of residuals
plot(nlsResiduals(mm), 6) # Normality of residuals
test.nlsResiduals(nlsResiduals(mm)) # Formal tests of normality and randomness
```


### Zadanie 3


```{r}
df <- drc::heartrate
mm <- nls(pressure ~ SSlogis(rate, a, b, c), data = df)


df |>
  ggplot(aes(y = pressure, x = rate)) +
  geom_point() +
  stat_function(fun = function(x) SSlogis(x, coef(mm)[1], coef(mm)[2], coef(mm)[3]))
```


```{r}
par(mfrow = c(2, 2))
plot(nlsResiduals(mm), 2) # Standardized residuals
plot(nlsResiduals(mm), 4) # Auto-correlation of residuals
plot(nlsResiduals(mm), 5) # Normality of residuals
plot(nlsResiduals(mm), 6) # Normality of residuals
test.nlsResiduals(nlsResiduals(mm)) # Formal tests of normality and randomness
```

```{r, echo=FALSE}
par(mfrow = c(1, 1))
```

### Zadanie 4

```{r}
df <- data.frame(
  t = 1:15,
  v = c(10, 16.3, 23, 27.5, 31, 35.6, 39, 41.5, 42.9, 45, 46, 45.5, 46, 49, 50)
)
mm <- nls(v ~ SSmicmen(t, a, b), data = df)
```

```{r}
par(mfrow = c(2, 2))
plot(nlsResiduals(mm), 2) # Standardized residuals
plot(nlsResiduals(mm), 4) # Auto-correlation of residuals
plot(nlsResiduals(mm), 5) # Normality of residuals
plot(nlsResiduals(mm), 6) # Normality of residuals
test.nlsResiduals(nlsResiduals(mm)) # Formal tests of normality and randomness
```

```{r}
df |>
    ggplot(aes(x = t, y = v)) +
    geom_point(data = data.frame(t = 18, 
                                 v = predict(mm, newdata = list(t = 18))),
               size = 4, colour = "red") +
    geom_point() +
    stat_function(fun = function(x) SSmicmen(x, coef(mm)[1], coef(mm)[2]))
```

### Zadanie 5

```{r}
df <- DAAG::moths

mm <- glm(formula = A ~ log(meters), data = df, family = poisson())
summary(mm)
```

Jest problem z obserwacjami odstającymi:

```{r}
par(mfrow = c(2, 2))
plot(mm, which = c(1:3, 5))
```

```{r}
df |> 
  ggplot(aes(y = A, x = meters)) +
  geom_point() +
  geom_smooth(method = "glm", formula = y ~ log(x), method.args = list(family = "poisson"))
```

```{r}
df |> 
  ggplot(aes(y = A, x = meters)) +
  geom_point() +
  geom_smooth(method = "glm", formula = y ~ log(x), method.args = list(family = "poisson"))
```

```{r}
mm <- glmrob(formula = A ~ log(meters), 
             data = df, 
             family = poisson(),
             method = "Mqle")
summary(mm)
```

```{r}
df |> 
  ggplot(aes(y = A, x = meters)) +
  geom_point() +
  stat_function(fun = function(x) predict(mm, newdata = list(meters = x), type = "response"))
```

### Zadanie 6

```{r}
grad <- readr::read_csv("https://drizzt.home.amu.edu.pl/images/DADA_AIPD/graduate.csv")
```
```{r}
mm1 <- glm(admit ~ gre + gpa + rank, 
           family = binomial(), 
           data = grad)

mm2 <- glm(admit ~ gre + gpa + as.factor(rank), 
           family = binomial(), 
           data = grad)
print(AIC(mm1, mm2))
print(BIC(mm1, mm2))
anova(mm1, mm2)
```

`mm1` jest lepszy niż `mm2`

```{r}
summary(mm1)
```

```{r}
par(mfrow = c(2, 2))
plot(mm1, which = c(1:3, 5))
```


```{r}
cbind(predict(mm1, type = "response"), grad$admit)
```

```{r}
df_pred <- data.frame(
  gre  = mean(grad$gre),
  gpa  = median(grad$gpa),
  rank = 1:4
)

cbind(df_pred, prob = predict(mm1, type = "response", 
        newdata = df_pred))
```

### Zadanie 7

```{r}
df <- data.frame(
  yes = rep(0:1, each = 11) |> factor(),
  weight = c(7, 1, 10, 9, 2, 9, 13, 1, 1, 4, 3,
             0, 0,  3, 4, 0, 6,  7, 0, 0, 1, 7),
  contr = rep(c(.1, .5, 1, 10, 20, 30, 50, 70, 80, 100, 150), 2)
)
```