---
title: "Ćwiczenia 7"
date: "2023-12-11"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(forecast)
```

### Zadanie 1

```{r}
print(c(
  "auto"  = difftime(as.Date("2000-12-31"), as.Date("1901-01-01")) |> as.numeric(),
  "secs"  = difftime(as.Date("2000-12-31"), as.Date("1901-01-01"), units = "secs") |> as.numeric(),
  "mins"  = difftime(as.Date("2000-12-31"), as.Date("1901-01-01"), units = "mins") |> as.numeric(),
  "hours" = difftime(as.Date("2000-12-31"), as.Date("1901-01-01"), units = "hours") |> as.numeric(),
  "days"  = difftime(as.Date("2000-12-31"), as.Date("1901-01-01"), units = "days") |> as.numeric(),
  "weeks" = difftime(as.Date("2000-12-31"), as.Date("1901-01-01"), units = "weeks") |> as.numeric()
))
```

### Zadanie 2

```{r}
data(wages, package = "TSA")
```

```{r}
autoplot(wages) +
  theme_minimal()
```

```{r}
df <- data.frame(
  y = wages |> as.numeric(),
  time = time(wages) |> as.numeric()
)
model_lin <- lm(y ~ time, data = df)
model_quad <- lm(y ~ time + I(time ^ 2), data = df)
print(summary(model_lin))
print(summary(model_quad))
print(AIC(model_lin, model_quad))
print(BIC(model_lin, model_quad))
print(shapiro.test(resid(model_lin)))
print(shapiro.test(resid(model_quad)))
```

```{r}
df |> 
  ggplot(aes(y = y, x = time)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE,
              aes(col = "Trend liniowy")) +
  geom_smooth(method = "lm", se = FALSE,
              formula = y ~ x + I(x ^ 2),
              aes(col = "Trend kwadratowy")) +
  scale_color_manual(values = c("Trend liniowy" = "salmon",
                                "Trend kwadratowy" = "lightgreen")) +
  labs(color = "Model trendu",
       x = "Średnia pensja",
       y = "Rok") +
  theme_bw()
```

```{r}
par(mfrow = c(2, 2))
plot(model_lin, which = c(1:3, 5))
```

```{r}
par(mfrow = c(2, 2))
plot(model_quad, which = c(1:3, 5))
```

### Zadanie 3

```{r}
df <- readr::read_csv("https://drizzt.home.amu.edu.pl/images/DADA_AIPD/female.txt", 
    col_names = FALSE)$X1 |> ts(start = c(1961, 7), frequency = 12)

#autoplot(forecast(df, h = 17))
model_ma <- arima(df, order = c(0, 0, 17))

autoplot(df) +
  geom_line(data = stats::filter(df, filter = rep(1, 17) / 17),
            colour = "red")  +
  geom_line(data = stats::filter(df, filter = rep(1, 12) / 12),
            colour = "green")
```

### Zadanie 4

```{r}
df <- readr::read_csv("https://drizzt.home.amu.edu.pl/images/DADA_AIPD/unemp.txt", 
    col_names = FALSE)$X1 |> ts(start = c(1975, 7), frequency = 12)

autoplot(df) +
  geom_line(data = stats::filter(df, filter = rep(1, 12) / 12),
            colour = "red")
tseries::adf.test(df, k = 12)
```

```{r}
HoltWinters(df)

autoplot(df) +
  geom_line(data = stats::filter(df, filter = rep(1, 12) / 12),
            aes(col = "Moving average"),
            linewidth = 2) +
  geom_line(data = forecast(HoltWinters(df))$fitted,
            aes(col = "HoltWinters"),
            linewidth = 2) +
  scale_color_manual(values = c("HoltWinters" = "blue",
                                "Moving average" = "red"))
```

### Zadanie 5

+ Badanie stacjonarności


Model ARMA(2, 1) / ARIMA(2, 0, 1)

```{r}
polyroot(c(1, -1, 1/4)) |> abs()
```

stacjonarny.

Model AR(2) / ARMA(2, 0) / ARIMA(2, 0, 0)

```{r}
polyroot(c(1, -2, -1)) |> abs()
```

nie jest stacjonarny.

Model ARMA(2, 2) / ARIMA(2, 0, 2)

```{r}
polyroot(c(1, -.5, .5)) |> abs()
```
stacjonarny.


### Zadanie 6

```{r}
polyroot(c(1, -3/2, 1/2)) |> abs()
```

Szereg nie jest stacjonarny.

```{r}
polyroot(c(1, -5/6, 1/6)) |> abs()
```

Szereg jest stacjonarny.

```{r}
polyroot(c(1, -2/3, 5/3)) |> abs()
```

Szereg nie jest stacjonarny

### Zadanie 7

```{r}
data(robot, package = "TSA")
m100 <- arima(robot, order = c(1, 0, 0))
m011 <- arima(robot, order = c(0, 1, 1))
AIC(m100, m011)
BIC(m100, m011)
```

```{r}
m_auto <- auto.arima(robot)
```

```{r}
forecast(m_auto, h = 5)
forecast(m011, h = 5)
forecast(m100, h = 5)
```
